= Gradle private repo plugin
:icons: font
:source-highlighter: rouge

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== About

Gradle plugin to configure private repository (Nexus, Artifactory) with sane defaults (for me).

IMPORTANT: Supports Gradle 6.8+.

Configured via gradle properties (e.g. in `~/.gradle/gradle.properties`).

.Configuration
|===
| Property | Description | Default | Example

| `nexusUrl` | Nexus base URL | -- | https://nexus.example.com
| `nexusUsername` | Nexus user name for repo | -- | deploy-user
| `nexusPassword` | Nexus user password for read access | -- | some-secret-password
| `nexusTarget` | Nexus repo or group to add | `public` |
| `nexusExclusive` | Use private repo as exclusive for groups and regexes | `false` |
| `nexusGroups` | Groups to exclude from Maven Central | empty | `com.example,org.example`
| `nexusGroupRegexes`| Regexes for groups to exclude when searching Maven Central | derived from `nexusUrl` base domain | `com\\.example(\\..*)?`
| `nexusDefaultGroupRegex` | Flag to enable generating default group regex from `nexusUrl` | `true` |
|===

CAUTION: `\` in `gradle.properties` requires escaping, so you have to use `\\.` instead of `\.`

.Effective additions to settings.gradle.kts
[source,kotlin]
----
pluginManagement {
  gradlePluginPortal()

  maven {
    name = "nexusReleasesGradle"
    url = uri("$nexusUrl/repository/gradle")
    mavenContent { releasesOnly() }
  }

  maven {
    name = "nexusSnapshotsGradle"
    url = uri("$nexusUrl/repository/gradle/dev")
    mavenContent { snapshotsOnly() }
  }
}

dependencyResolutionManagement {
  repositories {
    mavenCentral {
      groups.forEach { excludeGroup(it) }
      groupRegexes.forEach { excludeGroupByRegex(it) }
      // default exclude regex like `com\\.example(\\..*)?` is added if both `nexusGroups` and `nexusGroupRegexes` are empty
    }

    // when `nexusExclusive` not set or set to false
    maven {
      name = "nexus"
      url = uri("$nexusUrl/repository/$nexusTarget")

      // by default use `${name}Username` and `${name}Password` to authenticate
      credentials(PasswordCredentials::class.java)
      authentication.create<BasicAuthentication>("basic")
    }

    // when `nexusExclusive` is set to true
    exclusiveContent {
      forRepository {
        maven {
          name = "nexus"
          url = uri("$nexusUrl/repository/$nexusTarget")

          // by default use `${name}Username` and `${name}Password` to authenticate
          credentials(PasswordCredentials::class.java)
          authentication.create<BasicAuthentication>("basic")
        }
      }

      filter {
        groups.forEach { includeGroup(it) }
        groupRegexes.forEach { includeGroupByRegex(it) }
        // default include regex like `com\\.example(\\..*)?` is added if both `nexusGroups` and `nexusGroupRegexes` are empty
      }
    }
  }
}
----

== License

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
